import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

import streamlit as st
from agents.supervisor_agent import SupervisorAgent
from reports.report_generator import save_report
from dashboard.styles import apply_page_styling

apply_page_styling()

st.title("⊡ AI Executive Report")

st.markdown("""
<div style="font-size: 16px; color: #94a3b8; margin-bottom: 25px;">
Get a comprehensive, professional, print-ready business report generated by our multi-agent supervisor pipeline.
</div>
""", unsafe_allow_html=True)

if "df" not in st.session_state:
    st.markdown("""
    <div class="alert-box" style="border-left-color: #f59e0b;">
        <span style="font-weight: 600; color: #f59e0b;">⚠ Warning:</span> 
        <span style="color: #94a3b8;">Please upload a dataset first under <b>01 Upload Data</b>.</span>
    </div>
    """, unsafe_allow_html=True)
else:
    df = st.session_state["df"]

    # Initialize session state for caching the report
    if "cached_report" not in st.session_state:
        st.session_state["cached_report"] = None
        st.session_state["cached_report_file"] = None

    # Option to regenerate
    with st.sidebar:
        st.subheader("Report Actions")
        regenerate = st.button("↻ Regenerate Executive Report", type="primary", use_container_width=True)

    # If not cached or if user requested regeneration
    if st.session_state["cached_report"] is None or regenerate:
        with st.spinner("Generating multi-agent report... (Calling Groq Supervisor pipeline)"):
            try:
                supervisor = SupervisorAgent()
                result = supervisor.run(df)
                report_content = result["report"]
                
                # Verify report content
                if report_content.startswith("Error:") or "Limit Exceeded" in report_content or "Quota Exceeded" in report_content:
                    st.error(report_content)
                else:
                    # Save locally to disk
                    saved_path = save_report(report_content)
                    
                    st.session_state["cached_report"] = report_content
                    st.session_state["cached_report_file"] = saved_path
                    st.success("✦ Executive report generated and saved locally!")
            except Exception as e:
                st.error(f"Report generation failed: {str(e)}")
                st.info("✦ Make sure your GROQ_API_KEY is configured in your .env file.")

    # Show cached report if available
    if st.session_state["cached_report"] is not None:
        report_text = st.session_state["cached_report"]
        saved_file = st.session_state["cached_report_file"]
        
        # Show where it is saved on disk
        if saved_file:
            st.info(f"⊡ Report saved to: `{saved_file}`")
            
        # Download buttons
        col_dl1, col_dl2 = st.columns(2)
        with col_dl1:
            st.download_button(
                label="↓ Download Report (.md)",
                data=report_text,
                file_name=os.path.basename(saved_file) if saved_file else "executive_report.md",
                mime="text/markdown",
                use_container_width=True
            )
        with col_dl2:
            html_report = f"""<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>Executive Report</title>
<style>
body {{ font-family: 'Inter', -apple-system, sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; color: #1e293b; line-height: 1.6; }}
h1, h2, h3 {{ color: #0f172a; }}
pre {{ background: #f1f5f9; padding: 12px; border-radius: 6px; overflow-x: auto; }}
code {{ background: #f1f5f9; padding: 2px 6px; border-radius: 3px; font-size: 0.9em; }}
blockquote {{ border-left: 4px solid #6366f1; margin-left: 0; padding-left: 16px; color: #475569; }}
table {{ border-collapse: collapse; width: 100%; }}
th, td {{ border: 1px solid #e2e8f0; padding: 8px 12px; text-align: left; }}
th {{ background: #f8fafc; }}
@media print {{ body {{ margin: 0; padding: 20px; }} }}
</style></head>
<body>{report_text}</body></html>"""
            st.download_button(
                label="↓ Download as PDF (HTML)",
                data=html_report,
                file_name=(os.path.basename(saved_file).replace(".md", ".html") if saved_file else "executive_report.html"),
                mime="text/html",
                use_container_width=True,
                help="Save as HTML, then open in browser and print to PDF"
            )

        st.markdown("<div class='custom-card' style='border-top: 4px solid #6366f1; padding: 40px;'>", unsafe_allow_html=True)
        st.markdown(report_text)
        st.markdown("</div>", unsafe_allow_html=True)
