import sys
import os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

import streamlit as st
from agents.supervisor_agent import SupervisorAgent
from reports.report_generator import save_report
from dashboard.styles import apply_page_styling

st.set_page_config(layout="wide")
apply_page_styling()

st.title("📄 AI Executive Report")

st.markdown("""
<div style="font-size: 16px; color: #94a3b8; margin-bottom: 25px;">
Get a comprehensive, professional, print-ready business report generated by our multi-agent supervisor pipeline.
</div>
""", unsafe_allow_html=True)

if "df" not in st.session_state:
    st.markdown("""
    <div class="alert-box" style="border-left-color: #f59e0b;">
        <span style="font-weight: 600; color: #f59e0b;">⚠️ Warning:</span> 
        <span style="color: #94a3b8;">Please upload a dataset first under <b>01 Upload Data</b>.</span>
    </div>
    """, unsafe_allow_html=True)
else:
    df = st.session_state["df"]

    # Initialize session state for caching the report
    if "cached_report" not in st.session_state:
        st.session_state["cached_report"] = None
        st.session_state["cached_report_file"] = None

    # Option to regenerate
    with st.sidebar:
        st.subheader("Report Actions")
        regenerate = st.button("🔄 Regenerate Executive Report", type="primary", use_container_width=True)

    # If not cached or if user requested regeneration
    if st.session_state["cached_report"] is None or regenerate:
        with st.spinner("Generating multi-agent report... (Calling Groq Supervisor pipeline)"):
            try:
                supervisor = SupervisorAgent()
                result = supervisor.run(df)
                report_content = result["report"]
                
                # Verify report content
                if report_content.startswith("Error:") or "Limit Exceeded" in report_content or "Quota Exceeded" in report_content:
                    st.error(report_content)
                else:
                    # Save locally to disk
                    saved_path = save_report(report_content)
                    
                    st.session_state["cached_report"] = report_content
                    st.session_state["cached_report_file"] = saved_path
                    st.success("🎉 Executive report generated and saved locally!")
            except Exception as e:
                st.error(f"Report generation failed: {str(e)}")
                st.info("💡 Make sure your GROQ_API_KEY is configured in your .env file.")

    # Show cached report if available
    if st.session_state["cached_report"] is not None:
        report_text = st.session_state["cached_report"]
        saved_file = st.session_state["cached_report_file"]
        
        # Show where it is saved on disk
        if saved_file:
            st.info(f"💾 Report saved to: `{saved_file}`")
            
        # Download button
        st.download_button(
            label="📥 Download Report (.md)",
            data=report_text,
            file_name=os.path.basename(saved_file) if saved_file else "executive_report.md",
            mime="text/markdown",
            use_container_width=True
        )

        st.markdown("<div class='custom-card' style='border-top: 4px solid #6366f1; padding: 40px;'>", unsafe_allow_html=True)
        st.markdown(report_text)
        st.markdown("</div>", unsafe_allow_html=True)
